import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from '@/store/provider'
import Loader from '@/components/loader/loading'
import { Suspense } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Trading Materials', // should be updated dynamically
  description: 'Generated by create next app', // description should be updated 
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/fav-icon.png" sizes="any" />
      {/* <link rel='stylesheet' href="rsuite/dist/rsuite.css"/> */}
      
      </head>
      <body className={inter.className}>
       <Suspense fallback={ <Loader/>}>
      <Providers>{children}</Providers>
      </Suspense>

        </body>
    </html>
  )
}
